# Generated by Django 3.2.15 on 2022-09-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('senti', models.IntegerField(null=True)),
            ],
        ),
    ]
