# Generated by Django 3.2.15 on 2022-09-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_id',
            new_name='postid',
        ),
    ]
