# Generated by Django 3.2.15 on 2022-09-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_post_id_post_postid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('senti', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
